-- MySQL Script generated by MySQL Workbench
-- Mon Jul 17 09:42:23 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema yattell_database
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema yattell_database
-- -----------------------------------------------------
DROP DATABASE IF EXISTS `yattell_database`;
CREATE SCHEMA IF NOT EXISTS `yattell_database` DEFAULT CHARACTER SET utf8 ;
USE `yattell_database` ;

-- -----------------------------------------------------
-- Table `yattell_database`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yattell_database`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nickname` VARCHAR(45) NOT NULL,
  `user_type` VARCHAR(45) NOT NULL,
  `status` INT NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(50) NOT NULL,
  `profile_pic` VARCHAR(45) NULL,
  `create_time` DATETIME NOT NULL,
  `update_time` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `yattell_database`.`article`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yattell_database`.`article` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(256) NOT NULL,
  `summary` VARCHAR(512) NOT NULL,
  `status` INT NOT NULL,
  `views` INT NOT NULL,
  `content` VARCHAR(45) NOT NULL,
  `create_time` DATETIME NOT NULL,
  `update_time` DATETIME NOT NULL,
  `user_id` INT NOT NULL,
  `thumbnail` VARCHAR(521) NOT NULL,
  `punchline` VARCHAR(512) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `yattell_database`.`comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yattell_database`.`comment` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `memory` INT NOT NULL,
  `content` VARCHAR(160) NOT NULL,
  `commentable_type` VARCHAR(45) NOT NULL,
  `commentable_id` VARCHAR(45) NOT NULL,
  `status` INT NOT NULL,
  `create_time` DATETIME NOT NULL,
  `update_time` DATETIME NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `yattell_database`.`session`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yattell_database`.`session` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(256) NOT NULL,
  `status` INT NOT NULL,
  `create_time` DATETIME NOT NULL,
  `update_time` DATETIME NOT NULL,
  `user_id` INT NOT NULL,
  `article_id` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `yattell_database`.`viewHistory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yattell_database`.`viewHistory` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `target_type` VARCHAR(45) NOT NULL,
  `target_id` VARCHAR(45) NOT NULL,
  `status` INT NOT NULL,
  `create_time` DATETIME NOT NULL,
  `update_time` DATETIME NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `yattell_database`.`profile`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yattell_database`.`profile` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `middle_name` VARCHAR(45) NULL,
  `sex` VARCHAR(45) NULL,
  `company` VARCHAR(256) NULL,
  `job_title` VARCHAR(256) NULL,
  `address` VARCHAR(512) NULL,
  `contact_number` VARCHAR(45) NULL,
  `birthday` DATE NULL,
  `startup` INT NULL,
  `executive` INT NULL,
  `user_id` INT NOT NULL,
  `create_time` DATETIME NOT NULL,
  `update_time` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `yattell_database`.`comment_session`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yattell_database`.`comment_session` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `attitude` ENUM('agree', 'disagree') NOT NULL,
  `comments_id` INT NOT NULL,
  `session_id` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `yattell_database`.`security_info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yattell_database`.`security_info` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `security_question` VARCHAR(45) NOT NULL,
  `security_answer` VARCHAR(80) NOT NULL,
  `user_id` INT NOT NULL,
  `create_time` DATETIME NOT NULL,
  `update_time` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `yattell_database`.`likeSystem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yattell_database`.`likeSystem` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `status` VARCHAR(45) NOT NULL,
  `attitude` ENUM('like', 'dislike') NOT NULL,
  `user_id` INT NOT NULL,
  `likeable_id` INT NOT NULL,
  `likeable_type` VARCHAR(45) NOT NULL,
  `create_time` DATETIME NOT NULL,
  `update_time` DATETIME NOT NULL,
  `like_id` INT NOT NULL,
  `like_type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `yattell_database`.`tag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yattell_database`.`tag` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `status` INT NOT NULL,
  `create_time` DATETIME NOT NULL,
  `update_time` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `yattell_database`.`reply`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yattell_database`.`reply` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `memory` INT NOT NULL,
  `content` VARCHAR(160) NOT NULL,
  `comment_id` INT NOT NULL,
  `status` INT NOT NULL,
  `create_time` DATETIME NOT NULL,
  `update_time` DATETIME NOT NULL,
  `user_id` INT NOT NULL,
  `touser_id` INT NOT NULL,
  `reply_id` INT NOT NULL,
  `reply_type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `yattell_database`.`user_article_tag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yattell_database`.`user_article_tag` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tag_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `article_id` INT NOT NULL,
  `status` INT NOT NULL,
  `create_time` DATETIME NOT NULL,
  `update_time` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

INSERT INTO User (nickname, user_type, status, email, password, create_time, update_time) VALUES ('tony', 'admin', 1,'tony@yattell.com', md5('123456'),now(),now());
INSERT INTO User (nickname, user_type, status, email, password,create_time, update_time) VALUES ('nick', 'admin', 1,'nick@yattell.com', md5('123456'),now(),now());
INSERT INTO User (nickname, user_type, status, email, password,create_time, update_time) VALUES ('damon', 'admin', 1,'damon@yattell.com', md5('123456'),now(),now());
INSERT INTO User (nickname, user_type, status, email, password,create_time, update_time) VALUES ('Anonymous', 'basic', 1,'anonymous@yattell.com', md5('123456'),now(),now());

